"""rewrite

Revision ID: 0940740e37b2
Revises: f1b7c2807920
Create Date: 2026-07-24 16:13:49.288531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0940740e37b2'
down_revision = 'f1b7c2807920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gmail', sa.String(length=120), nullable=True))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('NINTH', 'TENTH', 'TWELFTH', name='gradelevel', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.Enum('NINTH', 'TENTH', 'TWELFTH', name='gradelevel', native_enum=False),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('gmail')

    # ### end Alembic commands ###
