"""Add tier column to Resource

Revision ID: 5cbca235825d
Revises: 0940740e37b2
Create Date: 2026-07-28 12:56:31.126040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5cbca235825d'
down_revision = '0940740e37b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'tier', 
                sa.Enum('FREE', 'PREMIUM', name='tiertype', native_enum=False), 
                nullable=False, 
                server_default='FREE'  # <--- Added this line
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('tier')

    op.create_table('purchases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount_paid', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('purchased_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('purchases_resource_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('purchases_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchases_pkey')),
    sa.UniqueConstraint('transaction_id', name=op.f('purchases_transaction_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
