"""sds

Revision ID: 7904d749d976
Revises: e89e1fc16a01
Create Date: 2026-07-23 14:15:11.141422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7904d749d976'
down_revision = 'e89e1fc16a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('gmail')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('tier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.VARCHAR(length=7), autoincrement=False, nullable=False))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gmail', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
