"""twelfth

Revision ID: f1b7c2807920
Revises: 7904d749d976
Create Date: 2026-07-24 16:01:18.608945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b7c2807920'
down_revision = '7904d749d976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('NINTH', 'TENTH', 'TWELTH', name='gradelevel', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.Enum('NINTH', 'TENTH', 'TWELTH', name='gradelevel', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)

    # ### end Alembic commands ###
